format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$docker_context\
$container\
$sudo\
$character
"""

right_format = """$time"""

[aws]
style = "bold #ffb86c"

[character]
# error_symbol = "[Î»](bold #ff5555)"
# success_symbol = "[Î»](bold #50fa7b)"
error_symbol = "[Î»](bold #E1E1D9)"
success_symbol = "[Î»](bold #E1E1D9)"
# success_symbol = "[ó°‡¹](bold #50fa7b)"
vimcmd_symbol = "[î˜«](bold #50fa7b)"


[cmd_duration]
disabled = true
style = "bold #f1fa8c"

[directory] 
truncation_length = 8
truncation_symbol = "â€¦/"
style = "bold #50fa7b"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bold #ff79c6"
format = '[$symbol $branch ]($style)'

[git_status]
format = '[\[$untracked$deleted$renamed$modified$staged$conflicted$ahead_behind\] ](fg:#ffffff)'
conflicted = '[$count îœ§ ](fg:#ff5555)'
untracked = '[$count[U](fg:#DC143C) ](fg:#DC143C)'
stashed = '[$countîª˜ ](fg:#ffae42)'
modified = '[$countï‘„ ](fg:#A9A9A9)'
staged = '[$count[S](fg:#6495ED) ](fg:#6495ED)'
renamed = '[$countâœ ](fg:#006400)'
deleted = '[$countï‘˜ ](fg:#FF4500)'
ahead = '[$countâ‡¡](fg:#008000)'
behind = '[$countâ‡£](fg:#008000)'


[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) "
style_user = "bold #8be9fd"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format

format = '[ $time ]($style)'
style = "bold #E1E1D9"

# format = '[ ï€— $time ]($style)'
# style = "bold #6495ED"

